Correct endpoint for post template
ONSdigital/rm-comms-template-service pull request #32
Opened 2018-03-19 14:17 UTC by jwgwalton

change from /templates/<id> to /templates

2018-03-19 14:29 UTC, tej99 requested changes
API.md needs updating

2018-03-26 10:25 UTC, madeye-matt approved these changes
Ideally the service should create the id for the newly created resource.  However as it appears to be validated  it should be safe as is so LGTM (but might want to change this in future iteration).

2018-03-26 10:31 UTC, jwgwalton commented
@tej99 I'd be lost without you and @gemmai95 reminding me to update the API.md's

2018-03-26 13:09 UTC, tej99 approved these changes

2018-03-26 13:19 UTC, merged