Changed so can pass arguments for different environments
ONSdigital/rm-comms-template-service pull request #41
Opened 2018-09-21 14:34 UTC by MIslam92

# Motivation and Context
Need to configure for different environments so changed to an argument based script

# What has changed
Passing in arguments now i.e. url, username and password

# How to test?
Simply run `pipenv run python ./scripts/config_comms_templates.py http://localhost:8182 admin secret`

To check if these templates get added 

# Links
Card: https://trello.com/c/pUPbT4Q0/336-ensure-all-comms-templates-are-configured-in-production-m

2018-09-21 14:46 UTC, andrewmil requested changes
You'll probably want a separate pipfile in the scripts folder to include your dependencies in.
`requests` isn't defined in the top level one

2018-09-21 14:46 UTC, andrewmil commented on scripts/config_comms_templates.py
> +    region = f'{args.default_url}/classificationtypes/REGION'
For consistency I'd define `args.default_url` as a variable

2018-09-21 14:46 UTC, andrewmil commented on scripts/config_comms_templates.py
>      contents = json.load(read_file)
You only need this line inside the `with` context manager. The rest doesn't need to be indented

2018-09-21 14:46 UTC, andrewmil commented on scripts/config_comms_templates.py
> +from flask import json
I'd just use the standard library `json` here

2018-09-24 08:01 UTC, tej99 approved these changes

2018-09-24 11:44 UTC, andrewmil approved these changes
Tested and works fine, left a few small comments but nothing serious

2018-09-24 11:44 UTC, andrewmil commented on scripts/config_comms_templates.py
> +    url = f'{arg_url}/templates'
This can be defined before the `for` loop

2018-09-24 11:44 UTC, andrewmil commented on scripts/config_existing_comms_template.py
> +parser = argparse.ArgumentParser(description='Pass in a service URL')
Description is out of date as we're now also passing in user/password

2018-09-24 11:44 UTC, andrewmil commented on scripts/config_comms_templates.py
> +# Run with the cmd pipenv run python scripts/config_comms_templates.py, 'url', 'user', 'password'
Don't need the commas here

2018-09-24 11:44 UTC, andrewmil commented on scripts/config_existing_comms_template.py
> +# Run with the cmd pipenv run python ./scripts/config_existing_comms_templates.py, 'url', 'user', 'password'
no need for commas here

2018-09-24 11:44 UTC, andrewmil commented on scripts/config_comms_templates.py
> +parser = argparse.ArgumentParser(description='Pass in a service URL')
Description is out of date as we're now also passing in user/password

2018-09-25 07:58 UTC, shahi645 approved these changes
Approving to merge 🌚

2018-09-25 07:59 UTC, merged